import { Roboto } from "next/font/google";
import "./globals.scss";
import Layout from "@/components/layout/Layout";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { AuthProvider } from "@/context/AuthContext";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "500", "700", "900"],
  style: ["normal", "italic"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  generator: "Next.js",
  manifest: "/manifest.json",
  keywords: ["nextjs", "next14", "pwa", "next-pwa"],
  themeColor: [{ media: "(prefers-color-scheme: dark", color: "fff" }],
  authors: [
    {
      name: "aralbai",
    },
  ],
  viewport:
    "minimum-scale=1, initial-scale=1, widht=device-width, shrink-to-fit=no, viewport-fit=cover",
  icons: [
    { rel: "apple-touch-icon", url: "icons/brain-512.png" },
    { rel: "icon", url: "icons/logo-512.png" },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="theme-color" content="#ffffff" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="icons/logo-512.png" />
        <link rel="apple-touch-icon" href="icons/logo-512.png" />
      </head>
      <body className={`${roboto.className}`}>
        <AuthProvider>
          <Layout>{children}</Layout>
          <ToastContainer position="top-right" autoClose={3000} />
        </AuthProvider>
      </body>
    </html>
  );
}
